name: firebase_saml
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  simple_logger: ^1.9.0+2
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
